# coding: utf-8

"""
    eLabNext REST API

    ## Authentication    To authenticate use the `POST /api/v1/auth/user` call below in the Authentication tab with a username and password. This will return an API token as property `token`.    All API calls, with the exception of authentication, need this API token in the header as `Authorization: [API token]`. Omitting this header or supplying an invalid API token results in an error 401 Not Authorized.    Example: `Authorization: eec0727eaf6f7b127aaec1ec33c21caf`    To use this with the **Try it out** buttons, fill in the **api_key** field above with the API token.    ## Request Bodies    The API uses JSON with character set UTF-8 for request and response bodies.    In any call that utilizes request bodies you must supply the header `Content-Type: application/json; charset=utf-8`.    ## Response Codes    Status Code | Name | Meaning  ----------- | ---- | -------  200 | OK | Success. (JSON) content is included in the body.  204 | No Content | Success and no body content. This status is always returned when a call does not produce content.  400 | Bad Request | Bad/missing parameters or JSON input.  401 | Not Authorized | Authentication header is missing or the supplied API token is invalid.  403 | Forbidden | The user associated with the API token has no permission for the requested operation.  404 | Not Found | The resource specified in the request does not exist.  405 | Method Not Allowed | The API call was made with an unsupported HTTP method. (e.g. GET instead of POST.)  409 | Conflict | A POST or PUT operation failed because it conflicts with existing data.  500 | Internal Server Error | A generic error occurred on the server. The response's `message` property contains a description of the error.        # noqa: E501

    OpenAPI spec version: v1
    Contact: enquiries@elabnext.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from elabjournal_client.configuration import Configuration


class PendingSignatureDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'prot_id': 'int',
        'protocol_name': 'str',
        'signed_by': 'SignatureProfileDTO',
        'witness': 'SignatureProfileDTO',
        'group_name': 'str',
        'signed_on': 'datetime'
    }

    attribute_map = {
        'prot_id': 'protID',
        'protocol_name': 'protocolName',
        'signed_by': 'signedBy',
        'witness': 'witness',
        'group_name': 'groupName',
        'signed_on': 'signedOn'
    }

    def __init__(self, prot_id=None, protocol_name=None, signed_by=None, witness=None, group_name=None, signed_on=None, _configuration=None):  # noqa: E501
        """PendingSignatureDTO - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._prot_id = None
        self._protocol_name = None
        self._signed_by = None
        self._witness = None
        self._group_name = None
        self._signed_on = None
        self.discriminator = None

        if prot_id is not None:
            self.prot_id = prot_id
        if protocol_name is not None:
            self.protocol_name = protocol_name
        if signed_by is not None:
            self.signed_by = signed_by
        if witness is not None:
            self.witness = witness
        if group_name is not None:
            self.group_name = group_name
        if signed_on is not None:
            self.signed_on = signed_on

    @property
    def prot_id(self):
        """Gets the prot_id of this PendingSignatureDTO.  # noqa: E501


        :return: The prot_id of this PendingSignatureDTO.  # noqa: E501
        :rtype: int
        """
        return self._prot_id

    @prot_id.setter
    def prot_id(self, prot_id):
        """Sets the prot_id of this PendingSignatureDTO.


        :param prot_id: The prot_id of this PendingSignatureDTO.  # noqa: E501
        :type: int
        """

        self._prot_id = prot_id

    @property
    def protocol_name(self):
        """Gets the protocol_name of this PendingSignatureDTO.  # noqa: E501


        :return: The protocol_name of this PendingSignatureDTO.  # noqa: E501
        :rtype: str
        """
        return self._protocol_name

    @protocol_name.setter
    def protocol_name(self, protocol_name):
        """Sets the protocol_name of this PendingSignatureDTO.


        :param protocol_name: The protocol_name of this PendingSignatureDTO.  # noqa: E501
        :type: str
        """

        self._protocol_name = protocol_name

    @property
    def signed_by(self):
        """Gets the signed_by of this PendingSignatureDTO.  # noqa: E501


        :return: The signed_by of this PendingSignatureDTO.  # noqa: E501
        :rtype: SignatureProfileDTO
        """
        return self._signed_by

    @signed_by.setter
    def signed_by(self, signed_by):
        """Sets the signed_by of this PendingSignatureDTO.


        :param signed_by: The signed_by of this PendingSignatureDTO.  # noqa: E501
        :type: SignatureProfileDTO
        """

        self._signed_by = signed_by

    @property
    def witness(self):
        """Gets the witness of this PendingSignatureDTO.  # noqa: E501


        :return: The witness of this PendingSignatureDTO.  # noqa: E501
        :rtype: SignatureProfileDTO
        """
        return self._witness

    @witness.setter
    def witness(self, witness):
        """Sets the witness of this PendingSignatureDTO.


        :param witness: The witness of this PendingSignatureDTO.  # noqa: E501
        :type: SignatureProfileDTO
        """

        self._witness = witness

    @property
    def group_name(self):
        """Gets the group_name of this PendingSignatureDTO.  # noqa: E501


        :return: The group_name of this PendingSignatureDTO.  # noqa: E501
        :rtype: str
        """
        return self._group_name

    @group_name.setter
    def group_name(self, group_name):
        """Sets the group_name of this PendingSignatureDTO.


        :param group_name: The group_name of this PendingSignatureDTO.  # noqa: E501
        :type: str
        """

        self._group_name = group_name

    @property
    def signed_on(self):
        """Gets the signed_on of this PendingSignatureDTO.  # noqa: E501


        :return: The signed_on of this PendingSignatureDTO.  # noqa: E501
        :rtype: datetime
        """
        return self._signed_on

    @signed_on.setter
    def signed_on(self, signed_on):
        """Sets the signed_on of this PendingSignatureDTO.


        :param signed_on: The signed_on of this PendingSignatureDTO.  # noqa: E501
        :type: datetime
        """

        self._signed_on = signed_on

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PendingSignatureDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PendingSignatureDTO):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PendingSignatureDTO):
            return True

        return self.to_dict() != other.to_dict()
