# coding: utf-8

"""
    eLabNext REST API

    ## Authentication    To authenticate use the `POST /api/v1/auth/user` call below in the Authentication tab with a username and password. This will return an API token as property `token`.    All API calls, with the exception of authentication, need this API token in the header as `Authorization: [API token]`. Omitting this header or supplying an invalid API token results in an error 401 Not Authorized.    Example: `Authorization: eec0727eaf6f7b127aaec1ec33c21caf`    To use this with the **Try it out** buttons, fill in the **api_key** field above with the API token.    ## Request Bodies    The API uses JSON with character set UTF-8 for request and response bodies.    In any call that utilizes request bodies you must supply the header `Content-Type: application/json; charset=utf-8`.    ## Response Codes    Status Code | Name | Meaning  ----------- | ---- | -------  200 | OK | Success. (JSON) content is included in the body.  204 | No Content | Success and no body content. This status is always returned when a call does not produce content.  400 | Bad Request | Bad/missing parameters or JSON input.  401 | Not Authorized | Authentication header is missing or the supplied API token is invalid.  403 | Forbidden | The user associated with the API token has no permission for the requested operation.  404 | Not Found | The resource specified in the request does not exist.  405 | Method Not Allowed | The API call was made with an unsupported HTTP method. (e.g. GET instead of POST.)  409 | Conflict | A POST or PUT operation failed because it conflicts with existing data.  500 | Internal Server Error | A generic error occurred on the server. The response's `message` property contains a description of the error.        # noqa: E501

    OpenAPI spec version: v1
    Contact: enquiries@elabnext.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from elabjournal_client.configuration import Configuration


class ProjectGroup(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'project_group_id': 'int',
        'subgroup_id': 'int',
        'name': 'str',
        'archived': 'bool',
        'created': 'datetime'
    }

    attribute_map = {
        'project_group_id': 'projectGroupID',
        'subgroup_id': 'subgroupID',
        'name': 'name',
        'archived': 'archived',
        'created': 'created'
    }

    def __init__(self, project_group_id=None, subgroup_id=None, name=None, archived=None, created=None, _configuration=None):  # noqa: E501
        """ProjectGroup - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._project_group_id = None
        self._subgroup_id = None
        self._name = None
        self._archived = None
        self._created = None
        self.discriminator = None

        if project_group_id is not None:
            self.project_group_id = project_group_id
        if subgroup_id is not None:
            self.subgroup_id = subgroup_id
        if name is not None:
            self.name = name
        if archived is not None:
            self.archived = archived
        if created is not None:
            self.created = created

    @property
    def project_group_id(self):
        """Gets the project_group_id of this ProjectGroup.  # noqa: E501


        :return: The project_group_id of this ProjectGroup.  # noqa: E501
        :rtype: int
        """
        return self._project_group_id

    @project_group_id.setter
    def project_group_id(self, project_group_id):
        """Sets the project_group_id of this ProjectGroup.


        :param project_group_id: The project_group_id of this ProjectGroup.  # noqa: E501
        :type: int
        """

        self._project_group_id = project_group_id

    @property
    def subgroup_id(self):
        """Gets the subgroup_id of this ProjectGroup.  # noqa: E501


        :return: The subgroup_id of this ProjectGroup.  # noqa: E501
        :rtype: int
        """
        return self._subgroup_id

    @subgroup_id.setter
    def subgroup_id(self, subgroup_id):
        """Sets the subgroup_id of this ProjectGroup.


        :param subgroup_id: The subgroup_id of this ProjectGroup.  # noqa: E501
        :type: int
        """

        self._subgroup_id = subgroup_id

    @property
    def name(self):
        """Gets the name of this ProjectGroup.  # noqa: E501


        :return: The name of this ProjectGroup.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ProjectGroup.


        :param name: The name of this ProjectGroup.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def archived(self):
        """Gets the archived of this ProjectGroup.  # noqa: E501


        :return: The archived of this ProjectGroup.  # noqa: E501
        :rtype: bool
        """
        return self._archived

    @archived.setter
    def archived(self, archived):
        """Sets the archived of this ProjectGroup.


        :param archived: The archived of this ProjectGroup.  # noqa: E501
        :type: bool
        """

        self._archived = archived

    @property
    def created(self):
        """Gets the created of this ProjectGroup.  # noqa: E501


        :return: The created of this ProjectGroup.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this ProjectGroup.


        :param created: The created of this ProjectGroup.  # noqa: E501
        :type: datetime
        """

        self._created = created

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProjectGroup, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectGroup):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProjectGroup):
            return True

        return self.to_dict() != other.to_dict()
