# coding: utf-8

"""
    eLabNext REST API

    ## Authentication    To authenticate use the `POST /api/v1/auth/user` call below in the Authentication tab with a username and password. This will return an API token as property `token`.    All API calls, with the exception of authentication, need this API token in the header as `Authorization: [API token]`. Omitting this header or supplying an invalid API token results in an error 401 Not Authorized.    Example: `Authorization: eec0727eaf6f7b127aaec1ec33c21caf`    To use this with the **Try it out** buttons, fill in the **api_key** field above with the API token.    ## Request Bodies    The API uses JSON with character set UTF-8 for request and response bodies.    In any call that utilizes request bodies you must supply the header `Content-Type: application/json; charset=utf-8`.    ## Response Codes    Status Code | Name | Meaning  ----------- | ---- | -------  200 | OK | Success. (JSON) content is included in the body.  204 | No Content | Success and no body content. This status is always returned when a call does not produce content.  400 | Bad Request | Bad/missing parameters or JSON input.  401 | Not Authorized | Authentication header is missing or the supplied API token is invalid.  403 | Forbidden | The user associated with the API token has no permission for the requested operation.  404 | Not Found | The resource specified in the request does not exist.  405 | Method Not Allowed | The API call was made with an unsupported HTTP method. (e.g. GET instead of POST.)  409 | Conflict | A POST or PUT operation failed because it conflicts with existing data.  500 | Internal Server Error | A generic error occurred on the server. The response's `message` property contains a description of the error.        # noqa: E501

    OpenAPI spec version: v1
    Contact: enquiries@elabnext.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from elabjournal_client.configuration import Configuration


class SampleLarge(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'owner': 'str',
        'quantity': 'str',
        'catalog_item': 'CatalogItem',
        'archived': 'bool',
        'delete_date': 'datetime',
        'checked_out_date': 'datetime',
        'expiration': 'datetime',
        'parent': 'SampleLarge',
        'children': 'list[SampleLarge]',
        'location': 'Location',
        'meta': 'list[SampleMetaBase]',
        'experiment_data': 'list[SampleExperiment]',
        'output_experiment_data': 'list[SampleExperiment]',
        'sample_id': 'int',
        'created': 'datetime',
        'user_id': 'int',
        'creator_id': 'int',
        'storage_layer_id': 'int',
        'position': 'int',
        'series_id': 'int',
        'barcode': 'str',
        'sample_type': 'SampleTypeShort',
        'sample_type_id': 'int',
        'checked_out': 'bool',
        'parent_sample_id': 'int',
        'name': 'str',
        'description': 'str',
        'note': 'str',
        'alt_id': 'str',
        'expiration_date': 'datetime'
    }

    attribute_map = {
        'owner': 'owner',
        'quantity': 'quantity',
        'catalog_item': 'catalogItem',
        'archived': 'archived',
        'delete_date': 'deleteDate',
        'checked_out_date': 'checkedOutDate',
        'expiration': 'expiration',
        'parent': 'parent',
        'children': 'children',
        'location': 'location',
        'meta': 'meta',
        'experiment_data': 'experimentData',
        'output_experiment_data': 'outputExperimentData',
        'sample_id': 'sampleID',
        'created': 'created',
        'user_id': 'userID',
        'creator_id': 'creatorID',
        'storage_layer_id': 'storageLayerID',
        'position': 'position',
        'series_id': 'seriesID',
        'barcode': 'barcode',
        'sample_type': 'sampleType',
        'sample_type_id': 'sampleTypeID',
        'checked_out': 'checkedOut',
        'parent_sample_id': 'parentSampleID',
        'name': 'name',
        'description': 'description',
        'note': 'note',
        'alt_id': 'altID',
        'expiration_date': 'expirationDate'
    }

    def __init__(self, owner=None, quantity=None, catalog_item=None, archived=None, delete_date=None, checked_out_date=None, expiration=None, parent=None, children=None, location=None, meta=None, experiment_data=None, output_experiment_data=None, sample_id=None, created=None, user_id=None, creator_id=None, storage_layer_id=None, position=None, series_id=None, barcode=None, sample_type=None, sample_type_id=None, checked_out=None, parent_sample_id=None, name=None, description=None, note=None, alt_id=None, expiration_date=None, _configuration=None):  # noqa: E501
        """SampleLarge - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._owner = None
        self._quantity = None
        self._catalog_item = None
        self._archived = None
        self._delete_date = None
        self._checked_out_date = None
        self._expiration = None
        self._parent = None
        self._children = None
        self._location = None
        self._meta = None
        self._experiment_data = None
        self._output_experiment_data = None
        self._sample_id = None
        self._created = None
        self._user_id = None
        self._creator_id = None
        self._storage_layer_id = None
        self._position = None
        self._series_id = None
        self._barcode = None
        self._sample_type = None
        self._sample_type_id = None
        self._checked_out = None
        self._parent_sample_id = None
        self._name = None
        self._description = None
        self._note = None
        self._alt_id = None
        self._expiration_date = None
        self.discriminator = None

        if owner is not None:
            self.owner = owner
        if quantity is not None:
            self.quantity = quantity
        if catalog_item is not None:
            self.catalog_item = catalog_item
        if archived is not None:
            self.archived = archived
        if delete_date is not None:
            self.delete_date = delete_date
        if checked_out_date is not None:
            self.checked_out_date = checked_out_date
        if expiration is not None:
            self.expiration = expiration
        if parent is not None:
            self.parent = parent
        if children is not None:
            self.children = children
        if location is not None:
            self.location = location
        if meta is not None:
            self.meta = meta
        if experiment_data is not None:
            self.experiment_data = experiment_data
        if output_experiment_data is not None:
            self.output_experiment_data = output_experiment_data
        if sample_id is not None:
            self.sample_id = sample_id
        if created is not None:
            self.created = created
        if user_id is not None:
            self.user_id = user_id
        if creator_id is not None:
            self.creator_id = creator_id
        if storage_layer_id is not None:
            self.storage_layer_id = storage_layer_id
        if position is not None:
            self.position = position
        if series_id is not None:
            self.series_id = series_id
        if barcode is not None:
            self.barcode = barcode
        if sample_type is not None:
            self.sample_type = sample_type
        self.sample_type_id = sample_type_id
        if checked_out is not None:
            self.checked_out = checked_out
        if parent_sample_id is not None:
            self.parent_sample_id = parent_sample_id
        self.name = name
        if description is not None:
            self.description = description
        if note is not None:
            self.note = note
        if alt_id is not None:
            self.alt_id = alt_id
        if expiration_date is not None:
            self.expiration_date = expiration_date

    @property
    def owner(self):
        """Gets the owner of this SampleLarge.  # noqa: E501


        :return: The owner of this SampleLarge.  # noqa: E501
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this SampleLarge.


        :param owner: The owner of this SampleLarge.  # noqa: E501
        :type: str
        """

        self._owner = owner

    @property
    def quantity(self):
        """Gets the quantity of this SampleLarge.  # noqa: E501


        :return: The quantity of this SampleLarge.  # noqa: E501
        :rtype: str
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this SampleLarge.


        :param quantity: The quantity of this SampleLarge.  # noqa: E501
        :type: str
        """

        self._quantity = quantity

    @property
    def catalog_item(self):
        """Gets the catalog_item of this SampleLarge.  # noqa: E501


        :return: The catalog_item of this SampleLarge.  # noqa: E501
        :rtype: CatalogItem
        """
        return self._catalog_item

    @catalog_item.setter
    def catalog_item(self, catalog_item):
        """Sets the catalog_item of this SampleLarge.


        :param catalog_item: The catalog_item of this SampleLarge.  # noqa: E501
        :type: CatalogItem
        """

        self._catalog_item = catalog_item

    @property
    def archived(self):
        """Gets the archived of this SampleLarge.  # noqa: E501


        :return: The archived of this SampleLarge.  # noqa: E501
        :rtype: bool
        """
        return self._archived

    @archived.setter
    def archived(self, archived):
        """Sets the archived of this SampleLarge.


        :param archived: The archived of this SampleLarge.  # noqa: E501
        :type: bool
        """

        self._archived = archived

    @property
    def delete_date(self):
        """Gets the delete_date of this SampleLarge.  # noqa: E501


        :return: The delete_date of this SampleLarge.  # noqa: E501
        :rtype: datetime
        """
        return self._delete_date

    @delete_date.setter
    def delete_date(self, delete_date):
        """Sets the delete_date of this SampleLarge.


        :param delete_date: The delete_date of this SampleLarge.  # noqa: E501
        :type: datetime
        """

        self._delete_date = delete_date

    @property
    def checked_out_date(self):
        """Gets the checked_out_date of this SampleLarge.  # noqa: E501


        :return: The checked_out_date of this SampleLarge.  # noqa: E501
        :rtype: datetime
        """
        return self._checked_out_date

    @checked_out_date.setter
    def checked_out_date(self, checked_out_date):
        """Sets the checked_out_date of this SampleLarge.


        :param checked_out_date: The checked_out_date of this SampleLarge.  # noqa: E501
        :type: datetime
        """

        self._checked_out_date = checked_out_date

    @property
    def expiration(self):
        """Gets the expiration of this SampleLarge.  # noqa: E501


        :return: The expiration of this SampleLarge.  # noqa: E501
        :rtype: datetime
        """
        return self._expiration

    @expiration.setter
    def expiration(self, expiration):
        """Sets the expiration of this SampleLarge.


        :param expiration: The expiration of this SampleLarge.  # noqa: E501
        :type: datetime
        """

        self._expiration = expiration

    @property
    def parent(self):
        """Gets the parent of this SampleLarge.  # noqa: E501


        :return: The parent of this SampleLarge.  # noqa: E501
        :rtype: SampleLarge
        """
        return self._parent

    @parent.setter
    def parent(self, parent):
        """Sets the parent of this SampleLarge.


        :param parent: The parent of this SampleLarge.  # noqa: E501
        :type: SampleLarge
        """

        self._parent = parent

    @property
    def children(self):
        """Gets the children of this SampleLarge.  # noqa: E501


        :return: The children of this SampleLarge.  # noqa: E501
        :rtype: list[SampleLarge]
        """
        return self._children

    @children.setter
    def children(self, children):
        """Sets the children of this SampleLarge.


        :param children: The children of this SampleLarge.  # noqa: E501
        :type: list[SampleLarge]
        """

        self._children = children

    @property
    def location(self):
        """Gets the location of this SampleLarge.  # noqa: E501


        :return: The location of this SampleLarge.  # noqa: E501
        :rtype: Location
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this SampleLarge.


        :param location: The location of this SampleLarge.  # noqa: E501
        :type: Location
        """

        self._location = location

    @property
    def meta(self):
        """Gets the meta of this SampleLarge.  # noqa: E501


        :return: The meta of this SampleLarge.  # noqa: E501
        :rtype: list[SampleMetaBase]
        """
        return self._meta

    @meta.setter
    def meta(self, meta):
        """Sets the meta of this SampleLarge.


        :param meta: The meta of this SampleLarge.  # noqa: E501
        :type: list[SampleMetaBase]
        """

        self._meta = meta

    @property
    def experiment_data(self):
        """Gets the experiment_data of this SampleLarge.  # noqa: E501


        :return: The experiment_data of this SampleLarge.  # noqa: E501
        :rtype: list[SampleExperiment]
        """
        return self._experiment_data

    @experiment_data.setter
    def experiment_data(self, experiment_data):
        """Sets the experiment_data of this SampleLarge.


        :param experiment_data: The experiment_data of this SampleLarge.  # noqa: E501
        :type: list[SampleExperiment]
        """

        self._experiment_data = experiment_data

    @property
    def output_experiment_data(self):
        """Gets the output_experiment_data of this SampleLarge.  # noqa: E501


        :return: The output_experiment_data of this SampleLarge.  # noqa: E501
        :rtype: list[SampleExperiment]
        """
        return self._output_experiment_data

    @output_experiment_data.setter
    def output_experiment_data(self, output_experiment_data):
        """Sets the output_experiment_data of this SampleLarge.


        :param output_experiment_data: The output_experiment_data of this SampleLarge.  # noqa: E501
        :type: list[SampleExperiment]
        """

        self._output_experiment_data = output_experiment_data

    @property
    def sample_id(self):
        """Gets the sample_id of this SampleLarge.  # noqa: E501


        :return: The sample_id of this SampleLarge.  # noqa: E501
        :rtype: int
        """
        return self._sample_id

    @sample_id.setter
    def sample_id(self, sample_id):
        """Sets the sample_id of this SampleLarge.


        :param sample_id: The sample_id of this SampleLarge.  # noqa: E501
        :type: int
        """

        self._sample_id = sample_id

    @property
    def created(self):
        """Gets the created of this SampleLarge.  # noqa: E501


        :return: The created of this SampleLarge.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this SampleLarge.


        :param created: The created of this SampleLarge.  # noqa: E501
        :type: datetime
        """

        self._created = created

    @property
    def user_id(self):
        """Gets the user_id of this SampleLarge.  # noqa: E501


        :return: The user_id of this SampleLarge.  # noqa: E501
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this SampleLarge.


        :param user_id: The user_id of this SampleLarge.  # noqa: E501
        :type: int
        """

        self._user_id = user_id

    @property
    def creator_id(self):
        """Gets the creator_id of this SampleLarge.  # noqa: E501


        :return: The creator_id of this SampleLarge.  # noqa: E501
        :rtype: int
        """
        return self._creator_id

    @creator_id.setter
    def creator_id(self, creator_id):
        """Sets the creator_id of this SampleLarge.


        :param creator_id: The creator_id of this SampleLarge.  # noqa: E501
        :type: int
        """

        self._creator_id = creator_id

    @property
    def storage_layer_id(self):
        """Gets the storage_layer_id of this SampleLarge.  # noqa: E501


        :return: The storage_layer_id of this SampleLarge.  # noqa: E501
        :rtype: int
        """
        return self._storage_layer_id

    @storage_layer_id.setter
    def storage_layer_id(self, storage_layer_id):
        """Sets the storage_layer_id of this SampleLarge.


        :param storage_layer_id: The storage_layer_id of this SampleLarge.  # noqa: E501
        :type: int
        """

        self._storage_layer_id = storage_layer_id

    @property
    def position(self):
        """Gets the position of this SampleLarge.  # noqa: E501


        :return: The position of this SampleLarge.  # noqa: E501
        :rtype: int
        """
        return self._position

    @position.setter
    def position(self, position):
        """Sets the position of this SampleLarge.


        :param position: The position of this SampleLarge.  # noqa: E501
        :type: int
        """

        self._position = position

    @property
    def series_id(self):
        """Gets the series_id of this SampleLarge.  # noqa: E501


        :return: The series_id of this SampleLarge.  # noqa: E501
        :rtype: int
        """
        return self._series_id

    @series_id.setter
    def series_id(self, series_id):
        """Sets the series_id of this SampleLarge.


        :param series_id: The series_id of this SampleLarge.  # noqa: E501
        :type: int
        """

        self._series_id = series_id

    @property
    def barcode(self):
        """Gets the barcode of this SampleLarge.  # noqa: E501


        :return: The barcode of this SampleLarge.  # noqa: E501
        :rtype: str
        """
        return self._barcode

    @barcode.setter
    def barcode(self, barcode):
        """Sets the barcode of this SampleLarge.


        :param barcode: The barcode of this SampleLarge.  # noqa: E501
        :type: str
        """

        self._barcode = barcode

    @property
    def sample_type(self):
        """Gets the sample_type of this SampleLarge.  # noqa: E501


        :return: The sample_type of this SampleLarge.  # noqa: E501
        :rtype: SampleTypeShort
        """
        return self._sample_type

    @sample_type.setter
    def sample_type(self, sample_type):
        """Sets the sample_type of this SampleLarge.


        :param sample_type: The sample_type of this SampleLarge.  # noqa: E501
        :type: SampleTypeShort
        """

        self._sample_type = sample_type

    @property
    def sample_type_id(self):
        """Gets the sample_type_id of this SampleLarge.  # noqa: E501


        :return: The sample_type_id of this SampleLarge.  # noqa: E501
        :rtype: int
        """
        return self._sample_type_id

    @sample_type_id.setter
    def sample_type_id(self, sample_type_id):
        """Sets the sample_type_id of this SampleLarge.


        :param sample_type_id: The sample_type_id of this SampleLarge.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and sample_type_id is None:
            raise ValueError("Invalid value for `sample_type_id`, must not be `None`")  # noqa: E501

        self._sample_type_id = sample_type_id

    @property
    def checked_out(self):
        """Gets the checked_out of this SampleLarge.  # noqa: E501


        :return: The checked_out of this SampleLarge.  # noqa: E501
        :rtype: bool
        """
        return self._checked_out

    @checked_out.setter
    def checked_out(self, checked_out):
        """Sets the checked_out of this SampleLarge.


        :param checked_out: The checked_out of this SampleLarge.  # noqa: E501
        :type: bool
        """

        self._checked_out = checked_out

    @property
    def parent_sample_id(self):
        """Gets the parent_sample_id of this SampleLarge.  # noqa: E501


        :return: The parent_sample_id of this SampleLarge.  # noqa: E501
        :rtype: int
        """
        return self._parent_sample_id

    @parent_sample_id.setter
    def parent_sample_id(self, parent_sample_id):
        """Sets the parent_sample_id of this SampleLarge.


        :param parent_sample_id: The parent_sample_id of this SampleLarge.  # noqa: E501
        :type: int
        """

        self._parent_sample_id = parent_sample_id

    @property
    def name(self):
        """Gets the name of this SampleLarge.  # noqa: E501


        :return: The name of this SampleLarge.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SampleLarge.


        :param name: The name of this SampleLarge.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this SampleLarge.  # noqa: E501


        :return: The description of this SampleLarge.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this SampleLarge.


        :param description: The description of this SampleLarge.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def note(self):
        """Gets the note of this SampleLarge.  # noqa: E501


        :return: The note of this SampleLarge.  # noqa: E501
        :rtype: str
        """
        return self._note

    @note.setter
    def note(self, note):
        """Sets the note of this SampleLarge.


        :param note: The note of this SampleLarge.  # noqa: E501
        :type: str
        """

        self._note = note

    @property
    def alt_id(self):
        """Gets the alt_id of this SampleLarge.  # noqa: E501


        :return: The alt_id of this SampleLarge.  # noqa: E501
        :rtype: str
        """
        return self._alt_id

    @alt_id.setter
    def alt_id(self, alt_id):
        """Sets the alt_id of this SampleLarge.


        :param alt_id: The alt_id of this SampleLarge.  # noqa: E501
        :type: str
        """

        self._alt_id = alt_id

    @property
    def expiration_date(self):
        """Gets the expiration_date of this SampleLarge.  # noqa: E501


        :return: The expiration_date of this SampleLarge.  # noqa: E501
        :rtype: datetime
        """
        return self._expiration_date

    @expiration_date.setter
    def expiration_date(self, expiration_date):
        """Sets the expiration_date of this SampleLarge.


        :param expiration_date: The expiration_date of this SampleLarge.  # noqa: E501
        :type: datetime
        """

        self._expiration_date = expiration_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SampleLarge, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SampleLarge):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SampleLarge):
            return True

        return self.to_dict() != other.to_dict()
