# coding: utf-8

"""
    eLabNext REST API

    ## Authentication    To authenticate use the `POST /api/v1/auth/user` call below in the Authentication tab with a username and password. This will return an API token as property `token`.    All API calls, with the exception of authentication, need this API token in the header as `Authorization: [API token]`. Omitting this header or supplying an invalid API token results in an error 401 Not Authorized.    Example: `Authorization: eec0727eaf6f7b127aaec1ec33c21caf`    To use this with the **Try it out** buttons, fill in the **api_key** field above with the API token.    ## Request Bodies    The API uses JSON with character set UTF-8 for request and response bodies.    In any call that utilizes request bodies you must supply the header `Content-Type: application/json; charset=utf-8`.    ## Response Codes    Status Code | Name | Meaning  ----------- | ---- | -------  200 | OK | Success. (JSON) content is included in the body.  204 | No Content | Success and no body content. This status is always returned when a call does not produce content.  400 | Bad Request | Bad/missing parameters or JSON input.  401 | Not Authorized | Authentication header is missing or the supplied API token is invalid.  403 | Forbidden | The user associated with the API token has no permission for the requested operation.  404 | Not Found | The resource specified in the request does not exist.  405 | Method Not Allowed | The API call was made with an unsupported HTTP method. (e.g. GET instead of POST.)  409 | Conflict | A POST or PUT operation failed because it conflicts with existing data.  500 | Internal Server Error | A generic error occurred on the server. The response's `message` property contains a description of the error.        # noqa: E501

    OpenAPI spec version: v1
    Contact: enquiries@elabnext.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from elabjournal_client.configuration import Configuration


class SampleTypeShort(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sample_type_id': 'int',
        'user_id': 'int',
        'group_id': 'int',
        'name': 'str',
        'background_color': 'str',
        'foreground_color': 'str',
        'show_sections_in_tabs': 'bool'
    }

    attribute_map = {
        'sample_type_id': 'sampleTypeID',
        'user_id': 'userID',
        'group_id': 'groupID',
        'name': 'name',
        'background_color': 'backgroundColor',
        'foreground_color': 'foregroundColor',
        'show_sections_in_tabs': 'showSectionsInTabs'
    }

    def __init__(self, sample_type_id=None, user_id=None, group_id=None, name=None, background_color=None, foreground_color=None, show_sections_in_tabs=None, _configuration=None):  # noqa: E501
        """SampleTypeShort - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._sample_type_id = None
        self._user_id = None
        self._group_id = None
        self._name = None
        self._background_color = None
        self._foreground_color = None
        self._show_sections_in_tabs = None
        self.discriminator = None

        if sample_type_id is not None:
            self.sample_type_id = sample_type_id
        if user_id is not None:
            self.user_id = user_id
        if group_id is not None:
            self.group_id = group_id
        if name is not None:
            self.name = name
        if background_color is not None:
            self.background_color = background_color
        if foreground_color is not None:
            self.foreground_color = foreground_color
        if show_sections_in_tabs is not None:
            self.show_sections_in_tabs = show_sections_in_tabs

    @property
    def sample_type_id(self):
        """Gets the sample_type_id of this SampleTypeShort.  # noqa: E501


        :return: The sample_type_id of this SampleTypeShort.  # noqa: E501
        :rtype: int
        """
        return self._sample_type_id

    @sample_type_id.setter
    def sample_type_id(self, sample_type_id):
        """Sets the sample_type_id of this SampleTypeShort.


        :param sample_type_id: The sample_type_id of this SampleTypeShort.  # noqa: E501
        :type: int
        """

        self._sample_type_id = sample_type_id

    @property
    def user_id(self):
        """Gets the user_id of this SampleTypeShort.  # noqa: E501


        :return: The user_id of this SampleTypeShort.  # noqa: E501
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this SampleTypeShort.


        :param user_id: The user_id of this SampleTypeShort.  # noqa: E501
        :type: int
        """

        self._user_id = user_id

    @property
    def group_id(self):
        """Gets the group_id of this SampleTypeShort.  # noqa: E501


        :return: The group_id of this SampleTypeShort.  # noqa: E501
        :rtype: int
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """Sets the group_id of this SampleTypeShort.


        :param group_id: The group_id of this SampleTypeShort.  # noqa: E501
        :type: int
        """

        self._group_id = group_id

    @property
    def name(self):
        """Gets the name of this SampleTypeShort.  # noqa: E501


        :return: The name of this SampleTypeShort.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SampleTypeShort.


        :param name: The name of this SampleTypeShort.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def background_color(self):
        """Gets the background_color of this SampleTypeShort.  # noqa: E501


        :return: The background_color of this SampleTypeShort.  # noqa: E501
        :rtype: str
        """
        return self._background_color

    @background_color.setter
    def background_color(self, background_color):
        """Sets the background_color of this SampleTypeShort.


        :param background_color: The background_color of this SampleTypeShort.  # noqa: E501
        :type: str
        """

        self._background_color = background_color

    @property
    def foreground_color(self):
        """Gets the foreground_color of this SampleTypeShort.  # noqa: E501


        :return: The foreground_color of this SampleTypeShort.  # noqa: E501
        :rtype: str
        """
        return self._foreground_color

    @foreground_color.setter
    def foreground_color(self, foreground_color):
        """Sets the foreground_color of this SampleTypeShort.


        :param foreground_color: The foreground_color of this SampleTypeShort.  # noqa: E501
        :type: str
        """

        self._foreground_color = foreground_color

    @property
    def show_sections_in_tabs(self):
        """Gets the show_sections_in_tabs of this SampleTypeShort.  # noqa: E501


        :return: The show_sections_in_tabs of this SampleTypeShort.  # noqa: E501
        :rtype: bool
        """
        return self._show_sections_in_tabs

    @show_sections_in_tabs.setter
    def show_sections_in_tabs(self, show_sections_in_tabs):
        """Sets the show_sections_in_tabs of this SampleTypeShort.


        :param show_sections_in_tabs: The show_sections_in_tabs of this SampleTypeShort.  # noqa: E501
        :type: bool
        """

        self._show_sections_in_tabs = show_sections_in_tabs

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SampleTypeShort, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SampleTypeShort):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SampleTypeShort):
            return True

        return self.to_dict() != other.to_dict()
