# coding: utf-8

"""
    eLabNext REST API

    ## Authentication    To authenticate use the `POST /api/v1/auth/user` call below in the Authentication tab with a username and password. This will return an API token as property `token`.    All API calls, with the exception of authentication, need this API token in the header as `Authorization: [API token]`. Omitting this header or supplying an invalid API token results in an error 401 Not Authorized.    Example: `Authorization: eec0727eaf6f7b127aaec1ec33c21caf`    To use this with the **Try it out** buttons, fill in the **api_key** field above with the API token.    ## Request Bodies    The API uses JSON with character set UTF-8 for request and response bodies.    In any call that utilizes request bodies you must supply the header `Content-Type: application/json; charset=utf-8`.    ## Response Codes    Status Code | Name | Meaning  ----------- | ---- | -------  200 | OK | Success. (JSON) content is included in the body.  204 | No Content | Success and no body content. This status is always returned when a call does not produce content.  400 | Bad Request | Bad/missing parameters or JSON input.  401 | Not Authorized | Authentication header is missing or the supplied API token is invalid.  403 | Forbidden | The user associated with the API token has no permission for the requested operation.  404 | Not Found | The resource specified in the request does not exist.  405 | Method Not Allowed | The API call was made with an unsupported HTTP method. (e.g. GET instead of POST.)  409 | Conflict | A POST or PUT operation failed because it conflicts with existing data.  500 | Internal Server Error | A generic error occurred on the server. The response's `message` property contains a description of the error.        # noqa: E501

    OpenAPI spec version: v1
    Contact: enquiries@elabnext.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from elabjournal_client.configuration import Configuration


class SDKTargetOrganisationMap(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sdk_plugin_target_organisation_id': 'int',
        'organisation_id': 'int',
        'sdk_plugin_id': 'int',
        'institute': 'Institute',
        'plugin': 'AddonPlugin'
    }

    attribute_map = {
        'sdk_plugin_target_organisation_id': 'sdkPluginTargetOrganisationID',
        'organisation_id': 'organisationID',
        'sdk_plugin_id': 'sdkPluginID',
        'institute': 'Institute',
        'plugin': 'Plugin'
    }

    def __init__(self, sdk_plugin_target_organisation_id=None, organisation_id=None, sdk_plugin_id=None, institute=None, plugin=None, _configuration=None):  # noqa: E501
        """SDKTargetOrganisationMap - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._sdk_plugin_target_organisation_id = None
        self._organisation_id = None
        self._sdk_plugin_id = None
        self._institute = None
        self._plugin = None
        self.discriminator = None

        if sdk_plugin_target_organisation_id is not None:
            self.sdk_plugin_target_organisation_id = sdk_plugin_target_organisation_id
        if organisation_id is not None:
            self.organisation_id = organisation_id
        if sdk_plugin_id is not None:
            self.sdk_plugin_id = sdk_plugin_id
        if institute is not None:
            self.institute = institute
        if plugin is not None:
            self.plugin = plugin

    @property
    def sdk_plugin_target_organisation_id(self):
        """Gets the sdk_plugin_target_organisation_id of this SDKTargetOrganisationMap.  # noqa: E501


        :return: The sdk_plugin_target_organisation_id of this SDKTargetOrganisationMap.  # noqa: E501
        :rtype: int
        """
        return self._sdk_plugin_target_organisation_id

    @sdk_plugin_target_organisation_id.setter
    def sdk_plugin_target_organisation_id(self, sdk_plugin_target_organisation_id):
        """Sets the sdk_plugin_target_organisation_id of this SDKTargetOrganisationMap.


        :param sdk_plugin_target_organisation_id: The sdk_plugin_target_organisation_id of this SDKTargetOrganisationMap.  # noqa: E501
        :type: int
        """

        self._sdk_plugin_target_organisation_id = sdk_plugin_target_organisation_id

    @property
    def organisation_id(self):
        """Gets the organisation_id of this SDKTargetOrganisationMap.  # noqa: E501


        :return: The organisation_id of this SDKTargetOrganisationMap.  # noqa: E501
        :rtype: int
        """
        return self._organisation_id

    @organisation_id.setter
    def organisation_id(self, organisation_id):
        """Sets the organisation_id of this SDKTargetOrganisationMap.


        :param organisation_id: The organisation_id of this SDKTargetOrganisationMap.  # noqa: E501
        :type: int
        """

        self._organisation_id = organisation_id

    @property
    def sdk_plugin_id(self):
        """Gets the sdk_plugin_id of this SDKTargetOrganisationMap.  # noqa: E501


        :return: The sdk_plugin_id of this SDKTargetOrganisationMap.  # noqa: E501
        :rtype: int
        """
        return self._sdk_plugin_id

    @sdk_plugin_id.setter
    def sdk_plugin_id(self, sdk_plugin_id):
        """Sets the sdk_plugin_id of this SDKTargetOrganisationMap.


        :param sdk_plugin_id: The sdk_plugin_id of this SDKTargetOrganisationMap.  # noqa: E501
        :type: int
        """

        self._sdk_plugin_id = sdk_plugin_id

    @property
    def institute(self):
        """Gets the institute of this SDKTargetOrganisationMap.  # noqa: E501


        :return: The institute of this SDKTargetOrganisationMap.  # noqa: E501
        :rtype: Institute
        """
        return self._institute

    @institute.setter
    def institute(self, institute):
        """Sets the institute of this SDKTargetOrganisationMap.


        :param institute: The institute of this SDKTargetOrganisationMap.  # noqa: E501
        :type: Institute
        """

        self._institute = institute

    @property
    def plugin(self):
        """Gets the plugin of this SDKTargetOrganisationMap.  # noqa: E501


        :return: The plugin of this SDKTargetOrganisationMap.  # noqa: E501
        :rtype: AddonPlugin
        """
        return self._plugin

    @plugin.setter
    def plugin(self, plugin):
        """Sets the plugin of this SDKTargetOrganisationMap.


        :param plugin: The plugin of this SDKTargetOrganisationMap.  # noqa: E501
        :type: AddonPlugin
        """

        self._plugin = plugin

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SDKTargetOrganisationMap, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SDKTargetOrganisationMap):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SDKTargetOrganisationMap):
            return True

        return self.to_dict() != other.to_dict()
