# coding: utf-8

"""
    eLabNext REST API

    ## Authentication    To authenticate use the `POST /api/v1/auth/user` call below in the Authentication tab with a username and password. This will return an API token as property `token`.    All API calls, with the exception of authentication, need this API token in the header as `Authorization: [API token]`. Omitting this header or supplying an invalid API token results in an error 401 Not Authorized.    Example: `Authorization: eec0727eaf6f7b127aaec1ec33c21caf`    To use this with the **Try it out** buttons, fill in the **api_key** field above with the API token.    ## Request Bodies    The API uses JSON with character set UTF-8 for request and response bodies.    In any call that utilizes request bodies you must supply the header `Content-Type: application/json; charset=utf-8`.    ## Response Codes    Status Code | Name | Meaning  ----------- | ---- | -------  200 | OK | Success. (JSON) content is included in the body.  204 | No Content | Success and no body content. This status is always returned when a call does not produce content.  400 | Bad Request | Bad/missing parameters or JSON input.  401 | Not Authorized | Authentication header is missing or the supplied API token is invalid.  403 | Forbidden | The user associated with the API token has no permission for the requested operation.  404 | Not Found | The resource specified in the request does not exist.  405 | Method Not Allowed | The API call was made with an unsupported HTTP method. (e.g. GET instead of POST.)  409 | Conflict | A POST or PUT operation failed because it conflicts with existing data.  500 | Internal Server Error | A generic error occurred on the server. The response's `message` property contains a description of the error.        # noqa: E501

    OpenAPI spec version: v1
    Contact: enquiries@elabnext.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class ProtocolLog(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'protlog_id': 'int',
        'prot_id': 'int',
        'prot_version_id': 'int',
        'user_id': 'int',
        'changed': 'datetime',
        'field': 'str',
        'log': 'str'
    }

    attribute_map = {
        'protlog_id': 'protlogID',
        'prot_id': 'protID',
        'prot_version_id': 'protVersionID',
        'user_id': 'userID',
        'changed': 'changed',
        'field': 'field',
        'log': 'log'
    }

    def __init__(self, protlog_id=None, prot_id=None, prot_version_id=None, user_id=None, changed=None, field=None, log=None, _configuration=None):  # noqa: E501
        """ProtocolLog - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._protlog_id = None
        self._prot_id = None
        self._prot_version_id = None
        self._user_id = None
        self._changed = None
        self._field = None
        self._log = None
        self.discriminator = None

        if protlog_id is not None:
            self.protlog_id = protlog_id
        if prot_id is not None:
            self.prot_id = prot_id
        if prot_version_id is not None:
            self.prot_version_id = prot_version_id
        if user_id is not None:
            self.user_id = user_id
        if changed is not None:
            self.changed = changed
        if field is not None:
            self.field = field
        if log is not None:
            self.log = log

    @property
    def protlog_id(self):
        """Gets the protlog_id of this ProtocolLog.  # noqa: E501


        :return: The protlog_id of this ProtocolLog.  # noqa: E501
        :rtype: int
        """
        return self._protlog_id

    @protlog_id.setter
    def protlog_id(self, protlog_id):
        """Sets the protlog_id of this ProtocolLog.


        :param protlog_id: The protlog_id of this ProtocolLog.  # noqa: E501
        :type: int
        """

        self._protlog_id = protlog_id

    @property
    def prot_id(self):
        """Gets the prot_id of this ProtocolLog.  # noqa: E501


        :return: The prot_id of this ProtocolLog.  # noqa: E501
        :rtype: int
        """
        return self._prot_id

    @prot_id.setter
    def prot_id(self, prot_id):
        """Sets the prot_id of this ProtocolLog.


        :param prot_id: The prot_id of this ProtocolLog.  # noqa: E501
        :type: int
        """

        self._prot_id = prot_id

    @property
    def prot_version_id(self):
        """Gets the prot_version_id of this ProtocolLog.  # noqa: E501


        :return: The prot_version_id of this ProtocolLog.  # noqa: E501
        :rtype: int
        """
        return self._prot_version_id

    @prot_version_id.setter
    def prot_version_id(self, prot_version_id):
        """Sets the prot_version_id of this ProtocolLog.


        :param prot_version_id: The prot_version_id of this ProtocolLog.  # noqa: E501
        :type: int
        """

        self._prot_version_id = prot_version_id

    @property
    def user_id(self):
        """Gets the user_id of this ProtocolLog.  # noqa: E501


        :return: The user_id of this ProtocolLog.  # noqa: E501
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this ProtocolLog.


        :param user_id: The user_id of this ProtocolLog.  # noqa: E501
        :type: int
        """

        self._user_id = user_id

    @property
    def changed(self):
        """Gets the changed of this ProtocolLog.  # noqa: E501


        :return: The changed of this ProtocolLog.  # noqa: E501
        :rtype: datetime
        """
        return self._changed

    @changed.setter
    def changed(self, changed):
        """Sets the changed of this ProtocolLog.


        :param changed: The changed of this ProtocolLog.  # noqa: E501
        :type: datetime
        """

        self._changed = changed

    @property
    def field(self):
        """Gets the field of this ProtocolLog.  # noqa: E501


        :return: The field of this ProtocolLog.  # noqa: E501
        :rtype: str
        """
        return self._field

    @field.setter
    def field(self, field):
        """Sets the field of this ProtocolLog.


        :param field: The field of this ProtocolLog.  # noqa: E501
        :type: str
        """

        self._field = field

    @property
    def log(self):
        """Gets the log of this ProtocolLog.  # noqa: E501


        :return: The log of this ProtocolLog.  # noqa: E501
        :rtype: str
        """
        return self._log

    @log.setter
    def log(self, log):
        """Sets the log of this ProtocolLog.


        :param log: The log of this ProtocolLog.  # noqa: E501
        :type: str
        """

        self._log = log

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProtocolLog, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProtocolLog):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProtocolLog):
            return True

        return self.to_dict() != other.to_dict()
